pipeline {
  agent any

  options {
    timestamps()
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install') {
      steps {
        sh 'corepack enable'
        sh 'pnpm install'
      }
    }

    stage('Build') {
      steps {
        sh 'pnpm --filter @dreisam/sdkpro-docs run build'
      }
    }
  }
}
