import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"API 接入指南","description":"","frontmatter":{},"headers":[],"relativePath":"api/access-guide.md","filePath":"api/access-guide.md"}');
const _sfc_main = { name: "api/access-guide.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="api-接入指南" tabindex="-1">API 接入指南 <a class="header-anchor" href="#api-接入指南" aria-label="Permalink to &quot;API 接入指南&quot;">​</a></h1><p>本文档基于 <code>DreisamAPIPro</code> 原始接入文档整理，用于说明 API 相关的基础接入要求。</p><h2 id="环境要求" tabindex="-1">环境要求 <a class="header-anchor" href="#环境要求" aria-label="Permalink to &quot;环境要求&quot;">​</a></h2><ul><li>最低系统版本：<code>iOS 11</code></li><li>开发环境：<code>Xcode</code></li><li>交付形式：<code>DreisamLibPro.framework</code></li></ul><h2 id="下载-sdk" tabindex="-1">下载 SDK <a class="header-anchor" href="#下载-sdk" aria-label="Permalink to &quot;下载 SDK&quot;">​</a></h2><blockquote><p><a href="https://github.com/Dreisam/DreisamLibPro-iOS" target="_blank" rel="noreferrer">DreisamLibPro-iOS</a></p></blockquote><p>仓库中包含：</p><ul><li><code>Demo</code>：示例工程</li><li><code>DreisamLib</code>：<code>DreisamLibPro.framework</code></li></ul><h2 id="接入步骤" tabindex="-1">接入步骤 <a class="header-anchor" href="#接入步骤" aria-label="Permalink to &quot;接入步骤&quot;">​</a></h2><h3 id="_1-添加-framework" tabindex="-1">1. 添加 Framework <a class="header-anchor" href="#_1-添加-framework" aria-label="Permalink to &quot;1. 添加 Framework&quot;">​</a></h3><p>将 <code>DreisamLibPro.framework</code> 加入工程并完成链接。</p><h3 id="_2-配置-info-plist" tabindex="-1">2. 配置 <code>Info.plist</code> <a class="header-anchor" href="#_2-配置-info-plist" aria-label="Permalink to &quot;2. 配置 \`Info.plist\`&quot;">​</a></h3><p>增加以下权限说明：</p><ul><li><code>Privacy - Bluetooth Peripheral Usage Description</code></li><li><code>Privacy - Bluetooth Always Usage Description</code></li></ul><h3 id="_3-初始化-sdk" tabindex="-1">3. 初始化 SDK <a class="header-anchor" href="#_3-初始化-sdk" aria-label="Permalink to &quot;3. 初始化 SDK&quot;">​</a></h3><div class="language-objective-c vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">objective-c</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">DreisamBuilderParam </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DreisamBuilderParam.new;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder.hideLog </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> NO</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder.appId </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> @&quot;******&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">[[DreisamLibManage </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">shareLib</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">] </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">initSDKBuilderParam:</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder];</span></span></code></pre></div><h2 id="说明" tabindex="-1">说明 <a class="header-anchor" href="#说明" aria-label="Permalink to &quot;说明&quot;">​</a></h2><p>原始文档中的截图资源未随仓库提供，因此这里改为结构化文字说明。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/access-guide.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const accessGuide = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  accessGuide as default
};
