import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Android SDK 接入指南","description":"","frontmatter":{},"headers":[],"relativePath":"sdk/android/access-guide.md","filePath":"sdk/android/access-guide.md"}');
const _sfc_main = { name: "sdk/android/access-guide.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="android-sdk-接入指南" tabindex="-1">Android SDK 接入指南 <a class="header-anchor" href="#android-sdk-接入指南" aria-label="Permalink to &quot;Android SDK 接入指南&quot;">​</a></h1><p>本文档说明如何将 <code>DreisamLib</code> 集成到 Android 项目中，并完成基础配置。</p><h2 id="环境要求" tabindex="-1">环境要求 <a class="header-anchor" href="#环境要求" aria-label="Permalink to &quot;环境要求&quot;">​</a></h2><ul><li>最低系统版本：<code>Android 8.0 / API 26</code></li><li>开发环境：<code>Android Studio</code></li><li>JDK：<code>Java 17</code></li></ul><h2 id="下载-sdk" tabindex="-1">下载 SDK <a class="header-anchor" href="#下载-sdk" aria-label="Permalink to &quot;下载 SDK&quot;">​</a></h2><p>SDK 仓库地址：</p><blockquote><p><a href="https://github.com/Dreisam/DreisamLib_Android" target="_blank" rel="noreferrer">DreisamLib_Android</a></p></blockquote><p>仓库中包含以下内容：</p><ul><li><code>Demo</code>：完整示例工程</li><li><code>libs</code>：包含 <code>DreisamLib-release_xxx.aar</code></li></ul><h2 id="接入步骤" tabindex="-1">接入步骤 <a class="header-anchor" href="#接入步骤" aria-label="Permalink to &quot;接入步骤&quot;">​</a></h2><h3 id="_1-添加-aar" tabindex="-1">1. 添加 AAR <a class="header-anchor" href="#_1-添加-aar" aria-label="Permalink to &quot;1. 添加 AAR&quot;">​</a></h3><p>将 <code>libs/DreisamLib-release_xxx.aar</code> 复制到业务工程的 <code>libs/</code> 目录，并在 <code>dependencies</code> 中引用：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>dependencies {</span></span>
<span class="line"><span>    implementation(files(&quot;libs/DreisamLib-release_xxx.aar&quot;))</span></span>
<span class="line"><span>}</span></span></code></pre></div><h3 id="_2-配置-build-gradle" tabindex="-1">2. 配置 <code>build.gradle</code> <a class="header-anchor" href="#_2-配置-build-gradle" aria-label="Permalink to &quot;2. 配置 \`build.gradle\`&quot;">​</a></h3><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>plugins {</span></span>
<span class="line"><span>    id(&quot;com.android.application&quot;)</span></span>
<span class="line"><span>    id(&quot;org.jetbrains.kotlin.android&quot;)</span></span>
<span class="line"><span>    id(&quot;org.jetbrains.kotlin.kapt&quot;)</span></span>
<span class="line"><span>}</span></span>
<span class="line"><span></span></span>
<span class="line"><span>android {</span></span>
<span class="line"><span>    namespace = &quot;com.dreisamlib.demo&quot;</span></span>
<span class="line"><span>    compileSdk = 35</span></span>
<span class="line"><span></span></span>
<span class="line"><span>    defaultConfig {</span></span>
<span class="line"><span>        applicationId = &quot;com.dreisam.demo&quot;</span></span>
<span class="line"><span>        minSdk = 26</span></span>
<span class="line"><span>        targetSdk = 36</span></span>
<span class="line"><span>        versionCode = 1</span></span>
<span class="line"><span>        versionName = &quot;1.0&quot;</span></span>
<span class="line"><span>    }</span></span>
<span class="line"><span>}</span></span>
<span class="line"><span></span></span>
<span class="line"><span>dependencies {</span></span>
<span class="line"><span>    implementation(files(&quot;libs/DreisamLib-release_xxx.aar&quot;))</span></span>
<span class="line"><span>    implementation(&quot;androidx.work:work-runtime-ktx:2.9.1&quot;)</span></span>
<span class="line"><span>    implementation(&quot;androidx.activity:activity:1.8.0&quot;)</span></span>
<span class="line"><span>    implementation(&quot;androidx.core:core-ktx:1.8.0&quot;)</span></span>
<span class="line"><span>    implementation(&quot;androidx.appcompat:appcompat:1.6.1&quot;)</span></span>
<span class="line"><span>    implementation(&quot;com.google.android.material:material:1.8.0&quot;)</span></span>
<span class="line"><span>    implementation(&quot;androidx.constraintlayout:constraintlayout:2.1.4&quot;)</span></span>
<span class="line"><span>    implementation(&quot;com.google.code.gson:gson:2.13.2&quot;)</span></span>
<span class="line"><span>    implementation(&quot;me.dm7.barcodescanner:zxing:1.9.4&quot;)</span></span>
<span class="line"><span>    implementation(&quot;com.github.getActivity:XXPermissions:26.0&quot;)</span></span>
<span class="line"><span>}</span></span></code></pre></div><h3 id="_3-添加蓝牙与定位权限" tabindex="-1">3. 添加蓝牙与定位权限 <a class="header-anchor" href="#_3-添加蓝牙与定位权限" aria-label="Permalink to &quot;3. 添加蓝牙与定位权限&quot;">​</a></h3><p>在 <code>AndroidManifest.xml</code> 中声明以下权限：</p><div class="language-xml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">xml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.BLUETOOTH&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.BLUETOOTH_ADMIN&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.ACCESS_FINE_LOCATION&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.ACCESS_COARSE_LOCATION&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.ACCESS_BACKGROUND_LOCATION&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.BLUETOOTH_SCAN&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    android:usesPermissionFlags</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;neverForLocation&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">uses-permission</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> android:name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;android.permission.BLUETOOTH_CONNECT&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /&gt;</span></span></code></pre></div><h3 id="_4-配置混淆" tabindex="-1">4. 配置混淆 <a class="header-anchor" href="#_4-配置混淆" aria-label="Permalink to &quot;4. 配置混淆&quot;">​</a></h3><p>在 <code>proguard-rules.pro</code> 中添加：</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>-keep class com.dreisamlib.lib.* {*;}</span></span></code></pre></div><h3 id="_5-初始化-sdk" tabindex="-1">5. 初始化 SDK <a class="header-anchor" href="#_5-初始化-sdk" aria-label="Permalink to &quot;5. 初始化 SDK&quot;">​</a></h3><p>完整能力见 <a href="./dreisamlib-api">DreisamLib API</a>。</p><h2 id="说明" tabindex="-1">说明 <a class="header-anchor" href="#说明" aria-label="Permalink to &quot;说明&quot;">​</a></h2><p>原始 Android 接入文档里的图片资源没有包含在当前仓库，因此这里统一改为文字化步骤。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("sdk/android/access-guide.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const accessGuide = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  accessGuide as default
};
