import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"iOS SDK 接入指南","description":"","frontmatter":{},"headers":[],"relativePath":"sdk/ios/access-guide.md","filePath":"sdk/ios/access-guide.md"}');
const _sfc_main = { name: "sdk/ios/access-guide.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="ios-sdk-接入指南" tabindex="-1">iOS SDK 接入指南 <a class="header-anchor" href="#ios-sdk-接入指南" aria-label="Permalink to &quot;iOS SDK 接入指南&quot;">​</a></h1><p>本文档说明如何将 <code>DreisamLibPro</code> 集成到 iOS 项目中，并完成基础初始化。</p><h2 id="环境要求" tabindex="-1">环境要求 <a class="header-anchor" href="#环境要求" aria-label="Permalink to &quot;环境要求&quot;">​</a></h2><ul><li>最低系统版本：<code>iOS 11</code></li><li>开发环境：<code>Xcode</code></li><li>交付形式：<code>DreisamLibPro.framework</code></li></ul><h2 id="下载-sdk" tabindex="-1">下载 SDK <a class="header-anchor" href="#下载-sdk" aria-label="Permalink to &quot;下载 SDK&quot;">​</a></h2><p>SDK 仓库地址：</p><blockquote><p><a href="https://github.com/Dreisam/DreisamLibPro-iOS" target="_blank" rel="noreferrer">DreisamLibPro-iOS</a></p></blockquote><p>仓库中包含以下内容：</p><ul><li><code>Demo</code>：完整示例工程，可用于了解标准接入流程。</li><li><code>DreisamLib</code>：包含 <code>DreisamLibPro.framework</code>。</li></ul><h2 id="接入步骤" tabindex="-1">接入步骤 <a class="header-anchor" href="#接入步骤" aria-label="Permalink to &quot;接入步骤&quot;">​</a></h2><h3 id="_1-添加-framework" tabindex="-1">1. 添加 Framework <a class="header-anchor" href="#_1-添加-framework" aria-label="Permalink to &quot;1. 添加 Framework&quot;">​</a></h3><p>将 <code>DreisamLibPro.framework</code> 加入 Xcode 工程，并确认目标 Target 已正确链接。</p><h3 id="_2-配置蓝牙权限" tabindex="-1">2. 配置蓝牙权限 <a class="header-anchor" href="#_2-配置蓝牙权限" aria-label="Permalink to &quot;2. 配置蓝牙权限&quot;">​</a></h3><p>在 <code>Info.plist</code> 中增加以下权限说明：</p><ul><li><code>Privacy - Bluetooth Peripheral Usage Description</code></li><li><code>Privacy - Bluetooth Always Usage Description</code></li></ul><h3 id="_3-初始化-sdk" tabindex="-1">3. 初始化 SDK <a class="header-anchor" href="#_3-初始化-sdk" aria-label="Permalink to &quot;3. 初始化 SDK&quot;">​</a></h3><div class="language-objective-c vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">objective-c</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">DreisamBuilderParam </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> DreisamBuilderParam.new;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder.hideLog </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> NO</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder.appId </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> @&quot;******&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">[[DreisamLibManage </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">shareLib</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">] </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">initSDKBuilderParam:</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">builder];</span></span></code></pre></div><p>参数说明：</p><ul><li><code>hideLog</code>：是否隐藏 SDK 日志，默认 <code>NO</code></li><li><code>appId</code>：开放平台生成的应用标识</li></ul><h3 id="_4-用户登录" tabindex="-1">4. 用户登录 <a class="header-anchor" href="#_4-用户登录" aria-label="Permalink to &quot;4. 用户登录&quot;">​</a></h3><div class="language-objective-c vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">objective-c</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">[DreisamLibManage.shareLib</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    loginUserToken:token</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">         callback:</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">^</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(DreisamEnumState state, DreisamDeviceModel </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> _Nonnull deviceModel) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">         }];</span></span></code></pre></div><h3 id="_5-绑定或连接设备" tabindex="-1">5. 绑定或连接设备 <a class="header-anchor" href="#_5-绑定或连接设备" aria-label="Permalink to &quot;5. 绑定或连接设备&quot;">​</a></h3><p>登录成功后，再继续执行绑定、连接和数据同步。完整能力见 <a href="./dreisamlib-api">DreisamLib API</a>。</p><h2 id="推荐顺序" tabindex="-1">推荐顺序 <a class="header-anchor" href="#推荐顺序" aria-label="Permalink to &quot;推荐顺序&quot;">​</a></h2><ol><li>下载 SDK 并导入 <code>DreisamLibPro.framework</code></li><li>配置 <code>Info.plist</code> 蓝牙权限</li><li>初始化 SDK</li><li>使用 <code>token</code> 登录</li><li>绑定设备</li><li>连接设备</li><li>监听状态与数据回调</li></ol><h2 id="说明" tabindex="-1">说明 <a class="header-anchor" href="#说明" aria-label="Permalink to &quot;说明&quot;">​</a></h2><p>原始接入文档中的图片使用的是本地绝对路径，当前仓库未提供对应资源，因此这里保留为文字化步骤。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("sdk/ios/access-guide.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const accessGuide = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  accessGuide as default
};
